### ISSUE TITLE
Spawnmenu icons break

### ISSUE THREAD

**Issue by Vlakobus1234** [Ec2dieBee/NSPW#1]
Idk if this mod is still being developed but when I tried out this mod the spawnmenu sections would be empty because it fails to load icons so you can't spawn any props from it. Is this a problem on my side or is it because the mod isn't finished yet?
Other than that, the mod works well.

**Comment by Ec2dieBee** [comment]
I haven't found this bug...(On normal branch)
Maybe something broken for no reason

**Comment by Vlakobus1234** [comment]
It seems to be working fine now, the spawnmenu no longer bugs out. So it's all good! Thank you for this mod

**Comment by Ec2dieBee** [comment]
Then I close this issue?
